spacetelescope/stsynphot_refactor

stsynphot/catalog.py, stsynphot/observationmode.py, stsynphot/spectrum.py, stsynphot/spparser.py, stsynphot/tests/test_catalog.py, stsynphot/tests/test_spectrum.py
Changes for spacetelescope/synphot_refactor#81
=> Use new models in synphot

.travis.yml, README.rst, appveyor.yml, stsynphot/__init__.py, stsynphot/_astropy_init.py, stsynphot/conftest.py, stsynphot/observationmode.py, stsynphot/spark.py, stsynphot/spectrum.py, stsynphot/spparser.py, stsynphot/stio.py, stsynphot/tests/test_config.py, stsynphot/tests/test_parser.py, stsynphot/tests/test_spectrum.py, stsynphot/tests/test_stio.py
Added egg_info, coverage, PEP8 tests for Travis CI. Added coveralls badge in README. Added optional commands to CIs. Fixed PEP8 issues.
Similar to spacetelescope/synphot_refactor#82
=> Expand Travis CI tests

stsynphot/spparser.py
Updated unit handling in parser to be more flexible. This is to catch up with spacetelescope/synphot_refactor#84.
=> Updated unit handling in parser to be more flexible

docs/conf.py, setup.py
Updated `astropy_helpers` to 1.2. Fixed `ConfigParser` compat with Python 3.
NOTE: Tests failed because of astropy/astropy#5178
=> Some updates

stsynphot/observationmode.py, stsynphot/spectrum.py, stsynphot/spparser.py, stsynphot/stio.py, stsynphot/tests/test_catalog.py, stsynphot/wavetable.py
Similar to spacetelescope/synphot_refactor#93. Also see astropy/astropy#5178.
=> Change how Quantity is defined to get around mag bug

stsynphot/observationmode.py, stsynphot/tests/test_observationmode.py, stsynphot/tests/test_spectrum.py
Fixed bug in thermal spectrum omitting some components, resulting in lower thermback values than expected.
=> Fixed bug in thermal spectrum

stsynphot/observationmode.py
Thermal spectrum algorithm now more similar to how ASTROLIB PYSYNPHOT does it
=> Improve thermal spectrum calculation

.gitignore, docs/stsynphot/tutorials.rst
Expand tutorials on zeropoints. Update `astropy-helpers`.
c/c @bhilbert4
=> Expand tutorials on zeropoints

docs/stsynphot/tutorials.rst
Based on https://gist.github.com/pllim/247348e605def564f9ca6e68acc77ac8 for Dr. Iskren Georgiev (private communication).
=> Add tutorial

docs/stsynphot/commissioning.rst, stsynphot/tests/test_spectrum.py
Fix test for spacetelescope/synphot_refactor#130. Updated doc.
xref spacetelescope/synphot_refactor#129
=> Fix test for extinction curve

ah_bootstrap.py, ez_setup.py
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
=> Update astropy-helpers to v2.0.2

docs/index.rst
Same as spacetelescope/pysynphot#71
=> Fix TSR doc link

docs/stsynphot/appendixa.rst, docs/stsynphot/spectrum.rst, stsynphot/catalog.py
Fix #43 
xref spacetelescope/pysynphot#77 and https://jira.stsci.edu/browse/REDCAT-47
=> Correct metallicity definition

CITATION, MANIFEST.in, docs/index.rst, docs/stsynphot/from_pysyn_iraf.rst, setup.cfg, stsynphot/commissioning/utils.py, stsynphot/observationmode.py
=> DOC: Add citation. Update help info.

.travis.yml, README.rst
Like spacetelescope/synphot_refactor#175
=> Use codecov for coverage report

docs/stsynphot/appendixa.rst, docs/stsynphot/data_atlas.rst
=> DOC: Add HLSP reference atlases URL

README.rst, azure-pipelines.yml
=> TST: Complete Azure transition

azure-templates.yml
=> Fix Windows job on Azure

CITATION, CITATION.md, MANIFEST.in, README.rst, docs/index.rst
=> Add Zenodo DOI

docs/index.rst, docs/stsynphot/appendixa.rst, docs/stsynphot/appendixb_nonhst.rst, docs/stsynphot/spectrum.rst, docs/stsynphot/tutorials.rst
Similar to spacetelescope/pysynphot#117 by @sean-lockwood .
=> DOC: Replace Zope links with Jahia

ah_bootstrap.py, docs/conf.py, setup.cfg, setup.py
Some warnings seen on install. Follow-up of #83
=> Fix helpers deprecation warnings

azure-pipelines.yml, azure-templates.yml
Ensure `stsynphot` works with astropy/astropy#8769.
Companion of spacetelescope/synphot_refactor#201
=> Test new models in astropy 4.0dev

docs/conf.py
=> DOC: Use HTTPS for intersphinx

.readthedocs.yml, azure-pipelines.yml, docs/conf.py
=> TST: Move PR doc build from Azure to RTD

.bandit.yaml, azure-pipelines.yml, stsynphot/spparser.py, stsynphot/stio.py
Report at https://innerspace.stsci.edu/display/DATB/Security+Audit+for+stsynphot_refactor .
Companion of spacetelescope/synphot_refactor#219
=> MNT: Security audit

stsynphot/tests/test_stio.py
Fix test failure uncovered by #89 that is unrelated to that PR.
=> Fix issubdtype in test

CHANGES.rst, stsynphot/tables.py, stsynphot/tests/test_tables.py
=> get_filename now raises GraphtabError

azure-pipelines.yml, docs/conf.py, docs/index.rst, docs/stsynphot/appendixa.rst, docs/stsynphot/appendixb.rst, docs/stsynphot/appendixb_inflight.rst, docs/stsynphot/appendixb_legacy.rst, docs/stsynphot/appendixb_nonhst.rst, docs/stsynphot/appendixb_specialkey.rst, docs/stsynphot/appendixc.rst, docs/stsynphot/commissioning.rst, docs/stsynphot/data_atlas.rst, docs/stsynphot/data_hst.rst, docs/stsynphot/data_jwst.rst, docs/stsynphot/from_pysyn_iraf.rst, docs/stsynphot/obsmode.rst, docs/stsynphot/overview.rst, docs/stsynphot/refdata.rst, docs/stsynphot/spectrum.rst, docs/stsynphot/tutorials.rst, setup.cfg, stsynphot/tests/test_parser.py, stsynphot/tests/test_spectrum.py, stsynphot/tests/test_stio.py
TODO:
Fix #57 
Fix #91 
Similar to spacetelescope/synphot_refactor#221
=> TST: doctest and linkcheck

docs/index.rst, docs/stsynphot/appendixa.rst, docs/stsynphot/data_atlas.rst
Fix #94 
Sean, can you please review? If you are okay with this, then I'll port the same content back to PySynphot. Thanks!
=> DOC: Add Brown Atlas to Appendix A

stsynphot/tests/test_tables.py
=> TST: Ignore FITS warning

CHANGES.rst, azure-pipelines.yml, azure-templates.yml, setup.cfg, stsynphot/config.py, stsynphot/spectrum.py, stsynphot/stio.py, stsynphot/tests/test_config.py, stsynphot/tests/test_parser.py, stsynphot/tests/test_stio.py, stsynphot/tests/test_tables.py
=> TST: Enable remote data tests on Windows

CHANGES.rst, stsynphot/commissioning/utils.py, stsynphot/observationmode.py, stsynphot/spark.py, stsynphot/spparser.py, stsynphot/stio.py, stsynphot/tables.py, stsynphot/tests/test_config.py, stsynphot/tests/test_observationmode.py, stsynphot/tests/test_parser.py, stsynphot/tests/test_spectrum.py, stsynphot/tests/test_stio.py, stsynphot/tests/test_tables.py, stsynphot/wavetable.py
=> BUG: Load lookup tables with no path

CHANGES.rst, docs/conf.py, docs/index.rst, docs/stsynphot/from_pysyn_iraf.rst, docs/stsynphot/tutorials.rst, setup.cfg, stsynphot/_astropy_init.py, stsynphot/catalog.py, stsynphot/commissioning/utils.py, stsynphot/config.py, stsynphot/conftest.py, stsynphot/observationmode.py, stsynphot/spark.py, stsynphot/spectrum.py, stsynphot/spparser.py, stsynphot/stio.py, stsynphot/tables.py, stsynphot/tests/test_parser.py, stsynphot/wavetable.py
=> MNT: Bump Python minversion to 3.6

.readthedocs.yml, CHANGES.rst, setup.cfg, stsynphot/catalog.py
Fix #45 
Since the original problem was only reported for the Phoenix catalog, this should be sufficient for now. Matplotlib allows zooming in, so things appearing small in screenshot is hopefully not a problem. This is the best I can make it without requiring user to manually page through each plot.
cc @mgennaro 
xref https://jira.stsci.edu/browse/REDCAT-48
=> ENH: Add plot_phoenix function

.github/workflows/ci_workflows.yml, docs/index.rst, docs/stsynphot/appendixa.rst, docs/stsynphot/data_hst.rst, docs/stsynphot/obsmode.rst, docs/stsynphot/refdata.rst, docs/stsynphot/tutorials.rst, stsynphot/config.py, stsynphot/stio.py, stsynphot/stsynphot.cfg, stsynphot/tests/test_stio.py, stsynphot/tests/test_tables.py
Address code change portion of #114 .
Companion to spacetelescope/synphot_refactor#278 and spacetelescope/pysynphot#135
=> Change CDBS to TRDS

CITATION.md, README.rst
Like spacetelescope/synphot_refactor#287
=> MNT: Use https

README.rst, docs/index.rst, docs/stsynphot/appendixb.rst, docs/stsynphot/appendixc.rst, docs/stsynphot/obsmode.rst, docs/stsynphot/overview.rst, setup.cfg
Will add back when things are less confusing, maybe.
Also see spacetelescope/synphot_refactor#288
=> DOC: Remove confusing mention of JWST

stsynphot/stio.py, stsynphot/tests/test_stio.py
As a result of astropy/astropy#11006
=> MNT: Compat with astropy 4.3

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, .github/labeler.yml, .github/workflows/ci_workflows.yml, .github/workflows/open_actions.yml
Similar to spacetelescope/synphot_refactor#289 and spacetelescope/synphot_refactor#290 .
=> TST: Update workflows and add templates

docs/conf.py, docs/stsynphot/appendixa.rst
This pull request is another attempt to fix broken links.
=> DOC: Fix links again

.github/workflows/ci_workflows.yml, tox.ini
This pull request is to address use `tox` to run tests.
=> TST: Use tox to run CI

.github/workflows/ci_workflows.yml, .github/workflows/codeql-analysis.yml
This pull request is to allow skipping CI without a failing status.
=> TST: Skip CI without fail

.github/workflows/publish-to-pypi.yml, stsynphot/tests/test_catalog.py
This pull request is to add wheel to release.
Fixes #136 
**TODO**
=> MNT: Update auto-release workflow 

docs/stsynphot/appendixa.rst
This pull request is to update link to the working version.
=> DOC: Old Castelli link back up

docs/conf.py, docs/stsynphot/appendixa.rst
See if adding `certifi` fixes SSL error when checking for www.sdss.org . Update: Nope, just ignore it for now.
=> TST: Fix linkcheck

docs/conf.py, docs/stsynphot/appendixb_nonhst.rst
Fix #141 now that IPAC has a new host for the page.
Follow up of #140
=> DOC: Fix 2MASS link

docs/stsynphot/appendixb_nonhst.rst
This pull request is to fix linkcheck job.
=> DOC: noao.edu is no more

docs/index.rst
This is an analogous change to spacetelescope/synphot_refactor#338.
=> Remove AstroConda installation instructions

.github/workflows/ci_workflows.yml, .github/workflows/publish-to-pypi.yml, CHANGES.rst, setup.cfg, stsynphot/stio.py, stsynphot/tests/test_stio.py, tox.ini
This pull request is to fix oldest deps job and update workflows.
See also https://github.com/spacetelescope/synphot_refactor/pull/341
=> TST: Fix oldest deps job, update workflows

.github/workflows/ci_workflows.yml, .github/workflows/predeps_workflow.yml, tox.ini
This pull request is to pin `tox<4` due to breaking changes and add RC testing.
Also see #169
I think #168 is resolved but let's see here.
=> TST: Pin tox<4 and add RC testing

.github/workflows/ci_workflows.yml, .github/workflows/publish-to-pypi.yml, .readthedocs.yaml, CHANGES.rst, conftest.py, docs/index.rst, setup.cfg, stsynphot/tests/test_spectrum.py, tox.ini
NumPy 2.0 compatibility and modernization to sync with corresponding synphot patch:
* https://github.com/spacetelescope/synphot_refactor/pull/363
=> NumPy 2.0 compatibility

.github/dependabot.yml
=> add GitHub Actions to dependabot

stsynphot/spectrum.py
"cripped" appears to be a typo for "crippled" (which can be offensive), so I reworded the warning message to use more inclusive language.
=> Fix wording in warning message

.github/workflows/publish-to-pypi.yml, CHANGES.rst, LICENSE, conftest.py, setup.cfg, stsynphot/__init__.py
This pull request is to fix #204
xref https://github.com/spacetelescope/synphot_refactor/pull/408
=> MNT: Remove astropy test runner, minor clean-ups
