- stsynphot/spectrum.py
- stsynphot/tests/test_spectrum.py
Replaced trapezoid integrator with `np.trapz()`. Replaced "array_like" with "array-like" in docstrings. This brings `stsynphot` up-to-date with spacetelescope/synphot_refactor#87.
> Replaced trapezoid integrator

- stsynphot/catalog.py
- stsynphot/tests/test_catalog.py
- stsynphot/tests/test_parser.py
Changed catalog names to be consistent with ASTROLIB PYSYNPHOT so that the same `parse_spec()` string works for both when creating an interpolated spectrum.
> Backward compatible catalog names

- stsynphot/observationmode.py
- stsynphot/spectrum.py
Use new `Empirical1D` that uses Nadia's new `Tabular` model.
TODO:
> Use new Empirical1D that uses new Tabular model

- stsynphot/commissioning/utils.py
- stsynphot/observationmode.py
- stsynphot/tables.py
Finally got around to fixing two outstanding issues that still exist in Astrolib PySynphot:
> Fix pysynphot OBSMODE limitations

- .travis.yml
- appveyor.yml
- setup.cfg
- setup.py
- stsynphot/commissioning/utils.py
- stsynphot/tests/test_catalog.py
- stsynphot/tests/test_config.py
- stsynphot/tests/test_observationmode.py
- stsynphot/tests/test_parser.py
- stsynphot/tests/test_spectrum.py
- stsynphot/tests/test_stio.py
- stsynphot/tests/test_tables.py
- stsynphot/tests/test_wavetable.py
Update Travis, Appveyor, and `astropy-helpers`. Use system `pytest`. Bump `pytest` minversion to 3.
See also spacetelescope/synphot_refactor#122
> Use system pytest and update astropy-helpers

- stsynphot/catalog.py
- stsynphot/tests/test_catalog.py
Fix #44 . Same solution as spacetelescope/pysynphot#70 . 
@mgennaro , do you want to take this for a spin and see if this is the fix you were looking for?
**To test this in your conda environment**
If you have previously cloned my fork, you can skip this
```
git clone https://github.com/pllim/stsynphot.git
```
Then
```
git checkout stop-gap
python setup.py install
```
> Error when catalog gap used in interpolation

- .travis.yml
- appveyor.yml
- docs/rtd-pip-requirements
- stsynphot/conftest.py
- stsynphot/stio.py
> MNT: Remove deprecation warning from np.issubdtype

- CHANGES.rst
- stsynphot/exceptions.py
- stsynphot/spectrum.py
- stsynphot/tests/test_spectrum.py
`SynphotError` is too generic and HST ETC needs something more specific when pixel scale is undefined for thermal background calculations.
ref: [HETC-186](https://jira.stsci.edu/browse/HETC-186) for further discussions.
> Use PixscaleNotFoundError in thermback

- docs/index.rst
- docs/stsynphot/appendixb_nonhst.rst
This merge can wait until the TMG and TMC files are updated with the new OBSMODEs.
EDIT: xref spacetelescope/pysynphot#125
> Added 2MASS and WFIRST to Appendix B docs

- CHANGES.rst
- azure-pipelines.yml
- stsynphot/spparser.py
- stsynphot/tests/test_parser.py
Fix #102 
Address part of spacetelescope/synphot_refactor#237
**TODO**
> BUG: Fix parse_spec

- stsynphot/__init__.py
:crossed_fingers: 
xref conda-forge/stsynphot-feedstock#8 and conda-forge/stsynphot-feedstock#9
> MNT: So we can remove setuptools from conda-forge recipe

- .github/workflows/ci_workflows.yml
- docs/conf.py
Maybe I misunderstood the problem...
Close #119
> TST: linkcheck needs matplotlib to avoid warning, handle broken link

- docs/conf.py
This pull request is to un-ignore Phoenix catalog site in link check.
Fixes #122
> TST: Undo ignoring Phoenix site in link check

- tox.ini
This is an automated update made by the `batchpr` tool :robot: to because `astropy` has changed its default branch! You can report issues to @pllim.
> MNT: Update astropy default branch

- docs/conf.py
- docs/stsynphot/appendixb_nonhst.rst
This pull request updates the documentation in Appendix B for non-HST filters for the Roman Space Telescope. The TMG and TMC files in CRDS have been updated to rename the components to Roman, as well as renaming the F146 filter to W146, and adding the new F213 filter component. The documentation has been updated in this pull request to account for these changes.
> Updated Roman throughput to Phase C

- stsynphot/commissioning/utils.py
Direct import from `collections` is deprecated in Python 3.10. This causes the environment testing in https://github.com/spacetelescope/spacetelescope-env-distribution to fail:
```
/usr/share/miniconda/envs/spacetelescope-env-Linux-py3.10-latest/lib/python3.10/site-packages/stsynphot/commissioning/utils.py:6: in <module>
[29](https://github.com/spacetelescope/spacetelescope-env-distribution/runs/7429139594?check_suite_focus=true#step:11:30)
from collections import Iterable
[30](https://github.com/spacetelescope/spacetelescope-env-distribution/runs/7429139594?check_suite_focus=true#step:11:31)
E   ImportError: cannot import name 'Iterable' from 'collections' (/usr/share/miniconda/envs/spacetelescope-env-Linux-py3.10-latest/lib/python3.10/collections/__init__.py)
``` …
> fix for `collections` import deprecation

- stsynphot/tests/test_catalog.py
This pull request is to update Phoenix catalog test. It looks like Redcat has filled out the gaps for 2700 K in the grid but I still see the gap in 2200 K.
Example failure without this patch: https://github.com/spacetelescope/stsynphot_refactor/actions/runs/3785527395
c/c @mgennaro @vglaidler since they were involved in the original problem at https://github.com/spacetelescope/pysynphot/issues/68
xref #44 #48
> TST: Update Phoenix gap test case

- stsynphot/tests/test_catalog.py
Test added for #44 no longer emits expected warning. I think gaps are filled.
xref https://github.com/spacetelescope/pysynphot/issues/68#issuecomment-1402438980
> Remove test_phoenix_gap because all gaps now seemingly filled

- tox.ini
This pull request is to fix oldest deps failure due to involuntary numpy bump by asdf
> TST: asdf is bumping numpy in oldest deps so we need to pin it

- .github/workflows/check_milestone.yml
- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/open_actions.yml
- .github/workflows/predeps_workflow.yml
- .github/workflows/publish-to-pypi.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed
